HOTELS = [
    {
        "id": "H-CMB-001",
        "name": "Ocean Lantern Colombo",
        "city": "Colombo",
        "country": "Sri Lanka",
        "price_per_night_usd": 92,
        "rating": 4.6,
        "available_rooms": 8,
        "amenities": ["sea view", "breakfast", "airport pickup", "pool"],
    },
    {
        "id": "H-KDY-002",
        "name": "Kandy Cloud Retreat",
        "city": "Kandy",
        "country": "Sri Lanka",
        "price_per_night_usd": 71,
        "rating": 4.5,
        "available_rooms": 5,
        "amenities": ["mountain view", "spa", "breakfast"],
    },
    {
        "id": "H-PAR-003",
        "name": "Left Bank Atelier Hotel",
        "city": "Paris",
        "country": "France",
        "price_per_night_usd": 188,
        "rating": 4.7,
        "available_rooms": 3,
        "amenities": ["metro access", "breakfast", "family rooms"],
    },
    {
        "id": "H-TYO-004",
        "name": "Shibuya Sky Nest",
        "city": "Tokyo",
        "country": "Japan",
        "price_per_night_usd": 154,
        "rating": 4.8,
        "available_rooms": 6,
        "amenities": ["station access", "city view", "laundry"],
    },
]


FLIGHTS = [
    {
        "id": "F-CMB-DXB-101",
        "airline": "Emirates",
        "origin": "Colombo",
        "destination": "Dubai",
        "departure": "2026-08-14 10:15",
        "arrival": "2026-08-14 13:10",
        "price_usd": 354,
        "seats_available": 12,
    },
    {
        "id": "F-CMB-PAR-202",
        "airline": "Qatar Airways",
        "origin": "Colombo",
        "destination": "Paris",
        "departure": "2026-08-16 03:35",
        "arrival": "2026-08-16 14:20",
        "price_usd": 812,
        "seats_available": 7,
    },
    {
        "id": "F-CMB-TYO-303",
        "airline": "SriLankan Airlines",
        "origin": "Colombo",
        "destination": "Tokyo",
        "departure": "2026-09-02 22:45",
        "arrival": "2026-09-03 08:30",
        "price_usd": 640,
        "seats_available": 9,
    },
    {
        "id": "F-DXB-LON-404",
        "airline": "British Airways",
        "origin": "Dubai",
        "destination": "London",
        "departure": "2026-08-20 07:50",
        "arrival": "2026-08-20 12:15",
        "price_usd": 436,
        "seats_available": 15,
    },
]
