HOTELS = [
    {
        "id": "H-CMB-001",
        "name": "Ocean Lantern Colombo",
        "city": "Colombo",
        "country": "Sri Lanka",
        "price_per_night_usd": 92,
        "rating": 4.6,
        "available_rooms": 8,
        "amenities": ["sea view", "breakfast", "airport pickup", "pool"],
    },
    {
        "id": "H-KDY-002",
        "name": "Kandy Cloud Retreat",
        "city": "Kandy",
        "country": "Sri Lanka",
        "price_per_night_usd": 71,
        "rating": 4.5,
        "available_rooms": 5,
        "amenities": ["mountain view", "spa", "breakfast"],
    },
    {
        "id": "H-PAR-003",
        "name": "Left Bank Atelier Hotel",
        "city": "Paris",
        "country": "France",
        "price_per_night_usd": 188,
        "rating": 4.7,
        "available_rooms": 3,
        "amenities": ["metro access", "breakfast", "family rooms"],
    },
    {
        "id": "H-TYO-004",
        "name": "Shibuya Sky Nest",
        "city": "Tokyo",
        "country": "Japan",
        "price_per_night_usd": 154,
        "rating": 4.8,
        "available_rooms": 6,
        "amenities": ["station access", "city view", "laundry"],
    },
    {
        "id": "H-BKK-005",
        "name": "Siam Riverside Stay",
        "city": "Bangkok",
        "country": "Thailand",
        "price_per_night_usd": 84,
        "rating": 4.4,
        "available_rooms": 11,
        "amenities": ["river view", "breakfast", "near BTS"],
    },
    {
        "id": "H-SIN-006",
        "name": "Marina Garden Hotel",
        "city": "Singapore",
        "country": "Singapore",
        "price_per_night_usd": 176,
        "rating": 4.7,
        "available_rooms": 4,
        "amenities": ["metro access", "city view", "business lounge"],
    },
    {
        "id": "H-MUM-007",
        "name": "Mumbai Harbor Suites",
        "city": "Mumbai",
        "country": "India",
        "price_per_night_usd": 119,
        "rating": 4.3,
        "available_rooms": 9,
        "amenities": ["airport transfer", "breakfast", "family rooms"],
    },
]


FLIGHTS = [
    {
        "id": "F-CMB-DXB-101",
        "airline": "Emirates",
        "origin": "Colombo",
        "destination": "Dubai",
        "departure": "2026-08-14 10:15",
        "arrival": "2026-08-14 13:10",
        "price_usd": 354,
        "seats_available": 12,
    },
    {
        "id": "F-CMB-PAR-202",
        "airline": "Qatar Airways",
        "origin": "Colombo",
        "destination": "Paris",
        "departure": "2026-08-16 03:35",
        "arrival": "2026-08-16 14:20",
        "price_usd": 812,
        "seats_available": 7,
    },
    {
        "id": "F-CMB-TYO-303",
        "airline": "SriLankan Airlines",
        "origin": "Colombo",
        "destination": "Tokyo",
        "departure": "2026-09-02 22:45",
        "arrival": "2026-09-03 08:30",
        "price_usd": 640,
        "seats_available": 9,
    },
    {
        "id": "F-DXB-LON-404",
        "airline": "British Airways",
        "origin": "Dubai",
        "destination": "London",
        "departure": "2026-08-20 07:50",
        "arrival": "2026-08-20 12:15",
        "price_usd": 436,
        "seats_available": 15,
    },
    {
        "id": "F-BOM-DEL-505",
        "airline": "IndiGo",
        "origin": "Mumbai",
        "destination": "Delhi",
        "origin_code": "BOM",
        "destination_code": "DEL",
        "departure": "2026-08-11 08:10",
        "arrival": "2026-08-11 10:25",
        "price_usd": 96,
        "seats_available": 24,
    },
    {
        "id": "F-CMB-BKK-606",
        "airline": "Thai Airways",
        "origin": "Colombo",
        "destination": "Bangkok",
        "origin_code": "CMB",
        "destination_code": "BKK",
        "departure": "2026-08-18 01:20",
        "arrival": "2026-08-18 06:35",
        "price_usd": 289,
        "seats_available": 13,
    },
    {
        "id": "F-CMB-SIN-707",
        "airline": "Singapore Airlines",
        "origin": "Colombo",
        "destination": "Singapore",
        "origin_code": "CMB",
        "destination_code": "SIN",
        "departure": "2026-09-05 00:40",
        "arrival": "2026-09-05 07:05",
        "price_usd": 331,
        "seats_available": 10,
    },
]
